### PR TITLE
Fix: label all letters capitalized

### LINKED ISSUE #242: [Label] All letters are capitalize
### Current Behavior

All `Label` letters are capitalize.
Ex: "I'm A Label"

### Expected behavior

Only first letter should be capitalize
Ex: "I'm a label"

### Your environment

| Software         | Version |
| ---------------- | ------- |
| Faency version   |   1.0.0-5    |

### PR DESCRIPTION
**Pull request by seedy**
# Description

Closes #242 

`transform="capitalize"` now capitalizes only first letter.

Adds `transform="capitalizeWords"` in case previous behaviour may be of any use.

Updates stories for `Text` and `Label`

# Warnings

:warning: Added as comment in `Text`: this will only work with block elements (display block/inline-block)

Overriding `Text` or `Label` display might conflict with this variant

[source](https://developer.mozilla.org/en-US/docs/Web/CSS/::first-letter)

### CODE REVIEW

File: components/Text/Text.tsx [hunk 1]
```diff
@@ -76,8 +76,14 @@ export const Text = styled('span', {
         textTransform: 'uppercase',
       },
       capitalize: {
-        textTransform: 'capitalize',
+        // WARNING: this will only work with block elements (display block/inline-block)
+        '&::first-letter': {
```
Comment (seedy) [inline components/Text/Text.tsx:80]: :question: should I enforce a `display` value here to secure the behaviour ?

File: components/Text/Text.tsx [hunk 2]
```diff
@@ -76,8 +76,15 @@ export const Text = styled('span', {
         textTransform: 'uppercase',
       },
       capitalize: {
-        textTransform: 'capitalize',
+        // WARNING: this will only work with block elements (display block/inline-block)
+        // @see https://developer.mozilla.org/en-US/docs/Web/CSS/::first-letter
```
Comment (seedy) [inline components/Text/Text.tsx:80]: :question: should I enforce a `display` value for this variant to secure the behaviour ?

File: components/Text/Text.tsx [hunk 3]
```diff
@@ -76,8 +76,15 @@ export const Text = styled('span', {
...
+        '&::first-letter': {
```
Comment (seedy) [inline components/Text/Text.tsx:81]: :question: should I enforce a `display` value for this variant to secure the behaviour ?

Comment (paulocfjunior) [reply components/Text/Text.tsx:81]: I think you should, yes, `inline-block` as it's a Text element.

**Review by paulocfjunior — APPROVED** [review]

File: components/Text/Text.tsx (hunk 3 above)
Comment (seedy) [reply components/Text/Text.tsx]: Done. I also updated the default `display` - which was `block` - to `inline-block`

**Review by matthieuh — APPROVED** [review]
LGMT
