### PR TITLE
fix: Input, pass DOM node through useImperativehandle

### LINKED ISSUE #211: [Input+Tooltip] `useImperativeHandle` removes access to inner dom element, breaking `Tooltip`
### Description

`Input` component uses `useImperativeHandle` to give parent access to custom features.

`Tooltip` radix primitive requires to call `e.getBoundingClientRect` on wrapped element to properly display around it.
Therefore when it is wrapping an input, its display is broken

### PR DESCRIPTION
**Pull request by seedy**
### Description

Fixed inner `useImperativeHandle` inside `Input`, so that Radix tooltips can properly call `getClientBoundingRect` on them

### Close issues

Closes #211

### CODE REVIEW

File: components/Input/Input.tsx [hunk 1]
```diff
@@ -367,31 +367,25 @@ export interface HTMLInputProps extends React.InputHTMLAttributes<any> {
...
     React.useImperativeHandle(
       forwardedRef,
-      () => ({
-        clear: () => {
-          const { current } = inputRef;
-          if (current) {
-            current.value = '';
-          }
-        },
-        focus: () => {
```
Comment (seedy) [inline components/Input/Input.tsx:388]: :information_source: `focus` is already existing on dom node

File: components/Input/Input.tsx [hunk 2]
```diff
@@ -367,31 +367,25 @@ export interface HTMLInputProps extends React.InputHTMLAttributes<any> {
...
-          const { current } = inputRef;
-          if (current) {
-            current.focus();
-          }
-        },
-      }),
+      () => {
+        const { current } = inputRef;
+        if (current) {
+          current.clear = () => {
```
Comment (seedy) [inline components/Input/Input.tsx:383]: :information_source: I am mutating dom node to add custom features... I'm not really proud to apply mutations here, but the immutable alternative is not working:
```
return {
  ...current, // ignores dom node
  clear: () => }
};
```

**Review by paulocfjunior — APPROVED** [review]

**Review by matthieuh — APPROVED** [review]
LGTM
