### PR TITLE
fix: Select, proper variants and props typing

### LINKED ISSUE #198: [Select] size prop type is wrong
### Description

typing:
```
var size: (number & {
    "@motion"?: "small" | "medium" | "large" | undefined;
    "@bp1"?: "small" | "medium" | "large" | undefined;
    "@bp2"?: "small" | "medium" | "large" | undefined;
    "@bp3"?: "small" | "medium" | "large" | undefined;
    ... 4 more ...;
    "@initial"?: "small" | ... 2 more ... | undefined;
} & {
    ...;
}) | undefined
```

`size` prop is passed down to `SelectWrapper` and `StyledCaretSortIcon` which both expect `size` to be a stitches variant, excluding the `number` type.

### PR DESCRIPTION
**Pull request by seedy**
### Description

Rework Select variants and props.

Closes #198

### CODE REVIEW

**Review by paulocfjunior — APPROVED** [review]

**Review by matthieuh — COMMENTED** [review]
Type fix seems good to me. Regarding the `cursor` change could you explain what you tried to achieve/fix?

File: components/Select/Select.tsx [hunk 1]
```diff
@@ -235,7 +235,7 @@ export const Select = React.forwardRef<React.ElementRef<typeof StyledSelect>, Se
         disabled={props.disabled}
       >
         <StyledSelect ref={forwardedRef} {...props} />
-        <StyledCaretSortIcon size={size} />
+        <StyledCaretSortIcon size={size} cursor={cursor} />
```
Comment (seedy) [inline components/Select/Select.tsx:238]: @matthieuh I binded the `cursor` prop from `Select` down to `StyledCaretSortIcon`, as it has an unused `cursor` variant.

Do you think it's useful? Should I instead remove the variant from the subcomponent?

**Review by matthieuh — APPROVED** [review]
LGTM
